arb-dir: lib/l10n
template-arb-file: app_en.arb
untranslated-messages-file: untranslated_messages.txt
nullable-getter: false
output-dir: lib/generated
output-localization-file: app_localizations.dart
